### ISSUE TITLE
Corruption with Sub Applications

### ISSUE THREAD

**Issue by LB--** [ClickteamLLC/windows-edif#15]
Multiple users have been reporting extension corruption at runtime when sub-applications are present in the frame, even if they have nothing to do with the extension. I have had PMs from user _prester_, and _ProdigyX_ has started [this thread](http://community.clickteam.com/threads/80812-Extensions-vs-Sup-Apps) about it.

Prester informs me that both this official version of EDIF and my version of EDIF are affected.

@Andos @udp I have no idea what could be causing this, I am not familiar with how the internals of MMF2 work or why a sub application could affect extensions like this.

**Comment by steve-taylor** [comment]
My extension crashes its host runtime when instantiated inside a frame that belongs to a sub-application. This happens even when the object isn't used in any way.

My extension:
https://github.com/steve-taylor/mmf2-blowfish-cipher

MMF2 build 251 (can't upgrade yet).

**Comment by ClickT** [comment]
I didn't check your source code but it seems a fix hadn't been propagated to this version. An unitialized icon at runtime could cause a crash. This fix has just been pushed, try it.

**Comment by steve-taylor** [comment]
Thanks @ClickT. I updated to the latest commit, but sadly it still crashes when the sub-application whose contained frame contains my extension is instantiated.

**Comment by steve-taylor** [comment]
Same problem occurs in @LB--'s EDIF, even with this latest commit applied to it.

**Comment by steve-taylor** [comment]
I switched to @LB--'s EDIF and merged this change into that and I no longer get the crash. I don't know if the crash resolved just by his EDIF or by the combination of his EDIF and this fix.

**Comment by LB--** [comment]
I merged https://github.com/ClickteamLLC/windows-edif/commit/ab434ed64dcac30f76533cffd0b9143469173776 into https://github.com/LB--/windows-edif/commit/85338913b88f648dc7fdc2793853d63ebb19cddf so hopefully it should be fixed for anyone using my fork in the future. I'll ask ProdigyX to run his test case again and if it is fixed for him I'll close the issue.

**Comment by LB--** [comment]
Prester and ProdigyX both report that https://github.com/LB--/windows-edif/commit/85338913b88f648dc7fdc2793853d63ebb19cddf fixes their issue. Prester says that with https://github.com/ClickteamLLC/windows-edif/commit/ab434ed64dcac30f76533cffd0b9143469173776 the issue still happens, so probably the fix is in #18 - I'll close this issue and merge https://github.com/ClickteamLLC/windows-edif/commit/ab434ed64dcac30f76533cffd0b9143469173776 into #18
